baseurl = "http://docs.zammu.in"
languageCode = "en-us"
title = "Zammu Documentation"
theme = "readthedocs"
description = "This is a website where the documentation for https://zammu.in will be hosted."
